// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using socmed_backend.Data;

#nullable disable

namespace socmed_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308081949_Interactions")]
    partial class Interactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("socmed_backend.Models.Rant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rants");
                });

            modelBuilder.Entity("socmed_backend.Models.RantBookmark", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.ToTable("RantBookmarks");
                });

            modelBuilder.Entity("socmed_backend.Models.RantLike", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.ToTable("RantLikes");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReRant", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.ToTable("RantReRants");
                });

            modelBuilder.Entity("socmed_backend.Models.RantBookmark", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");
                });

            modelBuilder.Entity("socmed_backend.Models.RantLike", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReRant", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");
                });
#pragma warning restore 612, 618
        }
    }
}
