// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using socmed_backend.Data;

#nullable disable

namespace socmed_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315035023_AddQuoteRantId")]
    partial class AddQuoteRantId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("socmed_backend.Models.Follow", b =>
                {
                    b.Property<string>("FollowerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("socmed_backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("socmed_backend.Models.Rant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuoteRantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRantId");

                    b.HasIndex("UserId");

                    b.ToTable("Rants");
                });

            modelBuilder.Entity("socmed_backend.Models.RantBookmark", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RantBookmarks");
                });

            modelBuilder.Entity("socmed_backend.Models.RantLike", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RantLikes");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReRant", b =>
                {
                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RantReRants");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentReplyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RantId");

                    b.HasIndex("UserId");

                    b.ToTable("RantReplies");
                });

            modelBuilder.Entity("socmed_backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("socmed_backend.Models.Follow", b =>
                {
                    b.HasOne("socmed_backend.Models.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("socmed_backend.Models.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("socmed_backend.Models.Notification", b =>
                {
                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.Rant", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "QuoteRant")
                        .WithMany()
                        .HasForeignKey("QuoteRantId");

                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("Rants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.RantBookmark", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.RantLike", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReRant", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany()
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("ReRants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.RantReply", b =>
                {
                    b.HasOne("socmed_backend.Models.Rant", "Rant")
                        .WithMany("Replies")
                        .HasForeignKey("RantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("socmed_backend.Models.User", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("socmed_backend.Models.Rant", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("socmed_backend.Models.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Rants");

                    b.Navigation("ReRants");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
